#
## Created by PhpStorm.
## User: Nemzag aka Gaz‑mên Arifi (Shkypi, 1979-09-30) {https://github.com/Nemzag/}.
## Date: 2020-01-17
## Time: 14h41
## Updated:
#}
recaptcha:
  key: '%env(GOOGLE_RECAPTCHA_KEY)%'
  secret: '%env(GOOGLE_RECAPTCHA_SECRET)%'